#!/usr/bin/env bash
set -euo pipefail

readonly root_dir="$(cd "$(dirname "$0")/.." && pwd)"
readonly source_dir="$root_dir/assets/icons"
readonly output_file="$root_dir/main/status_icons.h"
readonly preview_file="$source_dir/status-icons-preview.png"
readonly size=32

for tool in inkscape convert montage sed; do
    command -v "$tool" >/dev/null || {
        echo "Missing required tool: $tool" >&2
        exit 1
    }
done

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

icons=(wifi-off cloud-off battery-exclamation)
{
    echo '#pragma once'
    echo
    echo '#include <stdint.h>'
    echo
    echo '/* Generated by tools/render_status_icons.sh from the vendored SVG sources. */'
} > "$output_file"

for icon in "${icons[@]}"; do
    # Render at 4x first so the final threshold preserves clean, sturdy 1-bit strokes.
    inkscape "$source_dir/$icon.svg" --export-filename="$tmp_dir/$icon.png" \
        --export-width=$((size * 4)) --export-height=$((size * 4)) >/dev/null
    convert "$tmp_dir/$icon.png" -background white -alpha remove -resize "${size}x${size}" \
        -threshold 50% -monochrome "xbm:$tmp_dir/$icon.xbm"
    sed -e 's/-/_/g' \
        -e "s/^#define \(.*\)/#define status_icon_\1/" \
        -e "s/^static char \(.*\)/static const uint8_t status_icon_\1/" \
        "$tmp_dir/$icon.xbm" >> "$output_file"
    printf '\n' >> "$output_file"
done

montage "$tmp_dir"/*.png -tile 4x1 -geometry 128x128+12+12 "$preview_file"
echo "Generated $output_file and $preview_file"
